### ISSUE TITLE
Add new buoys

### ISSUE THREAD

**Issue by kkoch** [glos/GLBuoys#10]
Add 45166 (Lake Champlain) and 45173 (Munising) buoy to glbuoys.

See also tickets for Data Portal.

**Comment by kkoch** [comment]
45173 is done.

**Comment by kkoch** [comment]
I see link to http://glbuoys.glos.us/45166 active and a marker on the map, but it doesn't appear on the listing on the main page - probably because it isn't in one of the GL's.  Maybe we need an "Other" section which could then also fit the ESF Sodus Bay stations that aren't actually on Lake Erie.  ????

**Comment by gcutrell** [comment]
I thought about it. Technically:
45014 is in Green Bay 
45020 is in Traverse bay
45143/45137 is in Georgian Bay
ESF2/ESF5 is in Sodus Bay
umbio is in some inland lake

Since buoy owners hasn't said anything I just kept it that way. I didn't have a lake to group 45166 into so I left it out of the tables. Making an "Other" section wouldn't be much trouble.
